name: cv
description: "A new Flutter project."

publish_to: "none"

version: 1.0.7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  riverpod_annotation: ^2.3.4
  go_router: ^13.2.0
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.3
  talker_flutter: ^4.0.3
  flutter_animate: ^4.5.0
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.5
  url_launcher_web: ^2.3.0

  # Firebase
  firebase_core: ^2.27.1

  flutter_markdown: ^0.6.21

  faker: ^2.1.0

  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  riverpod_lint: ^2.3.9
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.0
  go_router_builder: ^2.3.4
  riverpod_generator: ^2.3.11

  flutter_launcher_icons: ^0.13.1
  # dart run flutter_launcher_icons:main -f flutter_launcher_icons*

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/README/
